- name: Configure EC2 instance
  hosts: all
  become: true
  remote_user: ubuntu
  vars_files:
    - vars.yml

    
  tasks:
    - name: Ensure Nginx is installed
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true


    - name: configure the Nginx server
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/revers_proxy.conf
        mode: 0644
      notify: Restart Nginx

    - name: Remove default Nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    
    - name: Test Nginx configuration
      ansible.builtin.command: nginx -t
      register: nginx_test
      ignore_errors: yes

    - name: Show Nginx test output
      ansible.builtin.debug:
        var: nginx_test.stdout_lines


    - name: Start Nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: true

    - name: Configure reverse proxy

