name: CI/CD Pipeline

on:
  push:
    paths:
      - 'ansible/**'
      - 'app/**'
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'
  
jobs:
 
  deploy:
    name: Deploy Node.js Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into Server and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << EOF
            cd /app
            npm install
            pm2 restart all
          EOF
